
"""
Revision ID: 6b065f1eb006
Revises: None
Create Date: 2025-08-15 19:00:19.936582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b065f1eb006'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('tipoconta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipoconta_id'), 'tipoconta', ['id'], unique=False)
    op.create_table('tipotransacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipotransacao_id'), 'tipotransacao', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('datacriacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datalateracao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('valorInicial', sa.Float(), nullable=False),
    sa.Column('dataCriacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('idTipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idTipo'], ['tipoconta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conta_id'), 'conta', ['id'], unique=False)
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idReferencia', sa.Integer(), nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('idConta', sa.Integer(), nullable=False),
    sa.Column('idTipoTransacao', sa.Integer(), nullable=False),
    sa.Column('dataLancamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dataTransacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idCategoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['idConta'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['idTipoTransacao'], ['tipotransacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_id'), 'lancamentos', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_id'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_conta_id'), table_name='conta')
    op.drop_table('conta')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipotransacao_id'), table_name='tipotransacao')
    op.drop_table('tipotransacao')
    op.drop_index(op.f('ix_tipoconta_id'), table_name='tipoconta')
    op.drop_table('tipoconta')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###