
"""
Revision ID: 7786645cc501
Revises: None
Create Date: 2025-08-15 08:52:54.071001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7786645cc501'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('tipoconta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipoconta_id'), 'tipoconta', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('datacriacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datalateracao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('valorInicial', sa.Float(), nullable=False),
    sa.Column('dataCriacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('idTipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idTipo'], ['tipoconta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conta_id'), 'conta', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conta_id'), table_name='conta')
    op.drop_table('conta')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipoconta_id'), table_name='tipoconta')
    op.drop_table('tipoconta')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###