
"""
Revision ID: f8b937d85300
Revises: 7786645cc501
Create Date: 2025-08-15 10:35:12.616865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b937d85300'
down_revision = '7786645cc501'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipotransacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipotransacao_id'), 'tipotransacao', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipotransacao_id'), table_name='tipotransacao')
    op.drop_table('tipotransacao')
    # ### end Alembic commands ###